# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'O:\systemTool\python\lightTools\matteTool\objectIDExportUI.ui'
#
# Created: Wed Dec 02 13:26:57 2015
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from qtshim import QtCore, QtGui
from qtshim import Signal
from qtshim import wrapinstance


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_matteTools(object):
    def setupUi(self, matteTools):
        matteTools.setObjectName(_fromUtf8("matteTools"))
        matteTools.resize(456, 600)
        self.centralwidget = QtGui.QWidget(matteTools)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_6 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 3, 0, 1, 1)
        self.autoName_checkBox = QtGui.QCheckBox(self.frame)
        self.autoName_checkBox.setChecked(True)
        self.autoName_checkBox.setObjectName(_fromUtf8("autoName_checkBox"))
        self.gridLayout_4.addWidget(self.autoName_checkBox, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.override_checkBox = QtGui.QCheckBox(self.frame)
        self.override_checkBox.setChecked(False)
        self.override_checkBox.setObjectName(_fromUtf8("override_checkBox"))
        self.gridLayout_4.addWidget(self.override_checkBox, 2, 2, 1, 1)
        self.path_lineEdit = QtGui.QLineEdit(self.frame)
        self.path_lineEdit.setEnabled(False)
        self.path_lineEdit.setObjectName(_fromUtf8("path_lineEdit"))
        self.gridLayout_4.addWidget(self.path_lineEdit, 2, 1, 1, 1)
        self.showAll_checkBox = QtGui.QCheckBox(self.frame)
        self.showAll_checkBox.setChecked(True)
        self.showAll_checkBox.setObjectName(_fromUtf8("showAll_checkBox"))
        self.gridLayout_4.addWidget(self.showAll_checkBox, 3, 2, 1, 1)
        self.label = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 2, 0, 1, 1)
        self.name_lineEdit = QtGui.QLineEdit(self.frame)
        self.name_lineEdit.setText(_fromUtf8(""))
        self.name_lineEdit.setObjectName(_fromUtf8("name_lineEdit"))
        self.gridLayout_4.addWidget(self.name_lineEdit, 1, 1, 1, 1)
        self.dbFile_lineEdit = QtGui.QLineEdit(self.frame)
        self.dbFile_lineEdit.setObjectName(_fromUtf8("dbFile_lineEdit"))
        self.gridLayout_4.addWidget(self.dbFile_lineEdit, 3, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.project_comboBox = QtGui.QComboBox(self.frame)
        self.project_comboBox.setObjectName(_fromUtf8("project_comboBox"))
        self.gridLayout_4.addWidget(self.project_comboBox, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.id_tableWidget = QtGui.QTableWidget(self.frame)
        self.id_tableWidget.setMinimumSize(QtCore.QSize(220, 0))
        self.id_tableWidget.setObjectName(_fromUtf8("id_tableWidget"))
        self.id_tableWidget.setColumnCount(4)
        self.id_tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.id_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.id_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.id_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.id_tableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout_4.addWidget(self.id_tableWidget)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.assignObjectID_pushButton = QtGui.QPushButton(self.frame)
        self.assignObjectID_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.assignObjectID_pushButton.setObjectName(_fromUtf8("assignObjectID_pushButton"))
        self.horizontalLayout_3.addWidget(self.assignObjectID_pushButton)
        self.clearObjectID_pushButton = QtGui.QPushButton(self.frame)
        self.clearObjectID_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.clearObjectID_pushButton.setObjectName(_fromUtf8("clearObjectID_pushButton"))
        self.horizontalLayout_3.addWidget(self.clearObjectID_pushButton)
        self.horizontalLayout_3.setStretch(0, 3)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4.setStretch(0, 3)
        self.verticalLayout.addWidget(self.frame)
        matteTools.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(matteTools)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 456, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        matteTools.setMenuBar(self.menubar)

        self.retranslateUi(matteTools)
        QtCore.QObject.connect(self.override_checkBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.path_lineEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(matteTools)

    def retranslateUi(self, matteTools):
        matteTools.setWindowTitle(QtGui.QApplication.translate("matteTools", "MatteID Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("matteTools", "DB file : ", None, QtGui.QApplication.UnicodeUTF8))
        self.autoName_checkBox.setText(QtGui.QApplication.translate("matteTools", "Pipeline Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("matteTools", "Name : ", None, QtGui.QApplication.UnicodeUTF8))
        self.override_checkBox.setText(QtGui.QApplication.translate("matteTools", "Override", None, QtGui.QApplication.UnicodeUTF8))
        self.showAll_checkBox.setText(QtGui.QApplication.translate("matteTools", "Show All", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("matteTools", "Path : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("matteTools", "Project : ", None, QtGui.QApplication.UnicodeUTF8))
        item = self.id_tableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("matteTools", "ID", None, QtGui.QApplication.UnicodeUTF8))
        item = self.id_tableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("matteTools", "Asset", None, QtGui.QApplication.UnicodeUTF8))
        item = self.id_tableWidget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("matteTools", "Assigned", None, QtGui.QApplication.UnicodeUTF8))
        item = self.id_tableWidget.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("matteTools", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.assignObjectID_pushButton.setText(QtGui.QApplication.translate("matteTools", "Assign Object ID", None, QtGui.QApplication.UnicodeUTF8))
        self.clearObjectID_pushButton.setText(QtGui.QApplication.translate("matteTools", "Clear", None, QtGui.QApplication.UnicodeUTF8))

