# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'O:\systemTool\python\lightTools\matteTool\ui.ui'
#
# Created: Fri Feb 13 15:07:03 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from qtshim import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_matteTools(object):
    def setupUi(self, matteTools):
        matteTools.setObjectName(_fromUtf8("matteTools"))
        matteTools.resize(1000, 600)
        matteTools.setMinimumSize(QtCore.QSize(1000, 600))
        self.centralwidget = QtGui.QWidget(matteTools)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_2 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.autoName_checkBox = QtGui.QCheckBox(self.frame)
        self.autoName_checkBox.setChecked(True)
        self.autoName_checkBox.setObjectName(_fromUtf8("autoName_checkBox"))
        self.gridLayout_4.addWidget(self.autoName_checkBox, 0, 2, 1, 1)
        self.name_lineEdit = QtGui.QLineEdit(self.frame)
        self.name_lineEdit.setText(_fromUtf8(""))
        self.name_lineEdit.setObjectName(_fromUtf8("name_lineEdit"))
        self.gridLayout_4.addWidget(self.name_lineEdit, 0, 1, 1, 1)
        self.path_lineEdit = QtGui.QLineEdit(self.frame)
        self.path_lineEdit.setEnabled(False)
        self.path_lineEdit.setObjectName(_fromUtf8("path_lineEdit"))
        self.gridLayout_4.addWidget(self.path_lineEdit, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 1)
        self.showAll_checkBox = QtGui.QCheckBox(self.frame)
        self.showAll_checkBox.setChecked(True)
        self.showAll_checkBox.setObjectName(_fromUtf8("showAll_checkBox"))
        self.gridLayout_4.addWidget(self.showAll_checkBox, 2, 2, 1, 1)
        self.override_checkBox = QtGui.QCheckBox(self.frame)
        self.override_checkBox.setChecked(False)
        self.override_checkBox.setObjectName(_fromUtf8("override_checkBox"))
        self.gridLayout_4.addWidget(self.override_checkBox, 1, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.id_tableWidget = QtGui.QTableWidget(self.frame)
        self.id_tableWidget.setMinimumSize(QtCore.QSize(220, 0))
        self.id_tableWidget.setObjectName(_fromUtf8("id_tableWidget"))
        self.id_tableWidget.setColumnCount(4)
        self.id_tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.id_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.id_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.id_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.id_tableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout_4.addWidget(self.id_tableWidget)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.assignObjectID_pushButton = QtGui.QPushButton(self.frame)
        self.assignObjectID_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.assignObjectID_pushButton.setObjectName(_fromUtf8("assignObjectID_pushButton"))
        self.horizontalLayout_3.addWidget(self.assignObjectID_pushButton)
        self.clearObjectID_pushButton = QtGui.QPushButton(self.frame)
        self.clearObjectID_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.clearObjectID_pushButton.setObjectName(_fromUtf8("clearObjectID_pushButton"))
        self.horizontalLayout_3.addWidget(self.clearObjectID_pushButton)
        self.horizontalLayout_3.setStretch(0, 3)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_3 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_7.addWidget(self.label_3)
        self.project_comboBox = QtGui.QComboBox(self.frame)
        self.project_comboBox.setObjectName(_fromUtf8("project_comboBox"))
        self.horizontalLayout_7.addWidget(self.project_comboBox)
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_7.addWidget(self.label_7)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 2)
        self.horizontalLayout_7.setStretch(2, 4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_6 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.dbFile_lineEdit = QtGui.QLineEdit(self.frame)
        self.dbFile_lineEdit.setObjectName(_fromUtf8("dbFile_lineEdit"))
        self.horizontalLayout_8.addWidget(self.dbFile_lineEdit)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.matteID_tableWidget = QtGui.QTableWidget(self.frame)
        self.matteID_tableWidget.setObjectName(_fromUtf8("matteID_tableWidget"))
        self.matteID_tableWidget.setColumnCount(4)
        self.matteID_tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.matteID_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.matteID_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.matteID_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.matteID_tableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout_5.addWidget(self.matteID_tableWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.assignMatteID_pushButton = QtGui.QPushButton(self.frame)
        self.assignMatteID_pushButton.setEnabled(False)
        self.assignMatteID_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.assignMatteID_pushButton.setObjectName(_fromUtf8("assignMatteID_pushButton"))
        self.horizontalLayout_2.addWidget(self.assignMatteID_pushButton)
        self.createMultiMatte_pushButton = QtGui.QPushButton(self.frame)
        self.createMultiMatte_pushButton.setEnabled(False)
        self.createMultiMatte_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.createMultiMatte_pushButton.setObjectName(_fromUtf8("createMultiMatte_pushButton"))
        self.horizontalLayout_2.addWidget(self.createMultiMatte_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(12)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_4 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.multiMatteName_lineEdit = QtGui.QLineEdit(self.frame)
        self.multiMatteName_lineEdit.setText(_fromUtf8(""))
        self.multiMatteName_lineEdit.setObjectName(_fromUtf8("multiMatteName_lineEdit"))
        self.gridLayout_3.addWidget(self.multiMatteName_lineEdit, 1, 0, 1, 1)
        self.auto_checkBox = QtGui.QCheckBox(self.frame)
        self.auto_checkBox.setChecked(True)
        self.auto_checkBox.setObjectName(_fromUtf8("auto_checkBox"))
        self.gridLayout_3.addWidget(self.auto_checkBox, 1, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_3)
        self.multiMatte_listWidget = QtGui.QListWidget(self.frame)
        self.multiMatte_listWidget.setObjectName(_fromUtf8("multiMatte_listWidget"))
        self.verticalLayout_6.addWidget(self.multiMatte_listWidget)
        self.export_pushButton = QtGui.QPushButton(self.frame)
        self.export_pushButton.setEnabled(False)
        self.export_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.export_pushButton.setObjectName(_fromUtf8("export_pushButton"))
        self.verticalLayout_6.addWidget(self.export_pushButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.horizontalLayout_4.setStretch(0, 3)
        self.horizontalLayout_4.setStretch(1, 4)
        self.horizontalLayout_4.setStretch(2, 2)
        self.verticalLayout.addWidget(self.frame)
        matteTools.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(matteTools)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        matteTools.setMenuBar(self.menubar)

        self.retranslateUi(matteTools)
        QtCore.QObject.connect(self.override_checkBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.path_lineEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(matteTools)

    def retranslateUi(self, matteTools):
        matteTools.setWindowTitle(_translate("matteTools", "MatteID Manager", None))
        self.label_2.setText(_translate("matteTools", "Name : ", None))
        self.autoName_checkBox.setText(_translate("matteTools", "Pipeline Name", None))
        self.label.setText(_translate("matteTools", "Path : ", None))
        self.showAll_checkBox.setText(_translate("matteTools", "Show All", None))
        self.override_checkBox.setText(_translate("matteTools", "Override", None))
        item = self.id_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("matteTools", "ID", None))
        item = self.id_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("matteTools", "Asset", None))
        item = self.id_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("matteTools", "Assigned", None))
        item = self.id_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("matteTools", "Path", None))
        self.assignObjectID_pushButton.setText(_translate("matteTools", "Assign Object ID", None))
        self.clearObjectID_pushButton.setText(_translate("matteTools", "Clear", None))
        self.label_3.setText(_translate("matteTools", "Project : ", None))
        self.label_7.setText(_translate("matteTools", "-", None))
        self.label_6.setText(_translate("matteTools", "DB file : ", None))
        item = self.matteID_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("matteTools", "MatteID", None))
        item = self.matteID_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("matteTools", "VRayMtl", None))
        item = self.matteID_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("matteTools", "Multi Matte", None))
        item = self.matteID_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("matteTools", "  Color  ", None))
        self.assignMatteID_pushButton.setText(_translate("matteTools", "Assign Matte ID", None))
        self.createMultiMatte_pushButton.setText(_translate("matteTools", "Create Multi Matte", None))
        self.label_4.setText(_translate("matteTools", "Multi Matte", None))
        self.auto_checkBox.setText(_translate("matteTools", "Auto", None))
        self.export_pushButton.setText(_translate("matteTools", "Export to database", None))

